name: Build

on: [push, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: [kubernetes]
    container:
      image: openjdk:17-jdk-slim
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v3
      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: script
        run: ./gradlew --no-daemon clean build
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build/libs/*.jar
            build/classes/
            build/reports/
          retention-days: 5